[Baki/week8] Navigation(2)
SSUMC-6th/iOS_A pull request #62
Opened 2024-06-04 05:14 UTC by heemings

# 📍Summary
navigation 기능을 기용해 배민 장바구니 화면을 구현했습니다

# 💡PR Point
`NavigationLink(destination: OrderView(selectedSize: selectedSize, isGoldCrust: isGoldCrust))`
  selectView에서 selectedSize와 isGoldCrust 값이 정해지면 그 값을 OrderView로 넘기는 코드가 제일 중요한 부분인 것 같습니다!

# 🤔 Question

# 🔑 Simulator
![배민](https://github.com/SSUMC-6th/iOS_A/assets/162147724/fa6c99e2-af1d-4da5-9a4b-d259369d033c)

2024-06-04 22:08 UTC, jayn2u commented
.DS_Store만 해결하면 바로 병합할게.
8주차도 고생많았어.

2024-06-04 22:14 UTC, jayn2u requested changes
`.DS_Store`만 해결하면 바로 병합할게.
8주차도 고생많았어.

2024-06-05 17:42 UTC, kimsoomin20221789 approved these changes
수고했어~~

2024-06-05 17:42 UTC, kimsoomin20221789 commented on baki/baki_week8/baki_week8/ContentView.swift
> +        NavigationView {
`NavigationView`와 `NavigationStack`의 차이점에 대해 공부해보면 좋을 것 같아~

2024-06-05 17:42 UTC, kimsoomin20221789 commented on baki/baki_week8/baki_week8/OrderView.swift
> +                    Text("[재주문1위] 바싹불고기피자")
프로젝트를 시작할때는 백엔드 API 연동을 하기전에 프론트는 뷰를 먼저 만들어야할 거야. 그럴때 저 데이터인 불고기 피자 부분은 갈아끼워넣기 편하게 변수로 따로 빼놓는게 나중에 api 연동할 때 편할거야! 아래의 코드처럼~

``` swift
struct OrderView: View {
  var firstMenu: String = "[재주문1위] 바싹불고기피자"
    var body: some View {
      ...

          VStack(alignment: .leading) {
              Text("\(firstMenu)")
}
```

2024-06-10 08:45 UTC, jayn2u approved these changes
시험기간에 신경써줘서 고마워~

2024-06-10 08:45 UTC, merged